/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_712EC9DE__
#define __PLUGINEDITOR_H_712EC9DE__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class Tgconvol2AudioProcessorEditor  : public AudioProcessorEditor,
									   public Timer,
                                       public ButtonListener
{
public:
    Tgconvol2AudioProcessorEditor (Tgconvol2AudioProcessor* ownerFilter);
    ~Tgconvol2AudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void resized();
    void timerCallback();
    void buttonClicked (Button * button);
private: 
	ToggleButton bypassBtn;
    Label label;
    TextButton choiceButton;

	Tgconvol2AudioProcessor* getProcessor() const
    {
        return static_cast <Tgconvol2AudioProcessor*> (getAudioProcessor());
    }
};


#endif  // __PLUGINEDITOR_H_712EC9DE__
